### ISSUE TITLE
Is "Skype for Business" subscription needed to run the samples?

### ISSUE THREAD

**Issue by zywy** [OfficeDev/skype-ios-app-sdk-samples#5]
I'm wondering if we need the [subscription](https://products.office.com/en-US/skype-for-business/compare-plans?omkt=en-US) while development.

**Comment by richardtaylorrt** [comment]
Hi - yes, you do need a subscription.  If you don't have one, you can get a developer subscription here:
http://dev.office.com/devprogram 

The subscription is needed because you need a licensed Skype for Business user to:

- create a meeting: https://msdn.microsoft.com/en-us/skype/appsdk/getmeetingurl
- join that meeting as the remote 'agent' using the official Skype for Business apps for desktop or mobile: https://github.com/OfficeDev/skype-ios-app-sdk-samples/tree/master/BankingApp

For more on the overall "business to consumer" scenario supported by the SDK, see: https://msdn.microsoft.com/en-us/skype/appsdk/embedskypeb2ccomms .

By the way, you can also post questions in stackoverflow with SkypeDeveloper tag: http://stackoverflow.com/questions/tagged/skypedeveloper
